feat: Validate record name & type before deletion
gathertown/casper-3 pull request #41
Opened 2022-04-26 12:27 UTC by axilleastr

Records should be validated before the deletion. Casper-3 is allowed
to delete only records that are type `A` or `TXT` and their name is
the same with the fqdn input of the deleteRecord() function. In case
that the deleteRecord function processes records that don't fill these
requirements, the deletion should not happen

2022-04-26 12:46 UTC, hwoarang requested changes

2022-04-26 12:46 UTC, hwoarang commented on pkg/providers/cloudflare/dnsrecord.go
> +		if record.Name != fqdn || (record.Type != "TXT" && record.Type != "A") {
This check will fail if the `record.Name` is `fqdn` but type is CNAME for example. I believe you need something like
`if record.Name != fqdn && (record.Type != "TXT" && record.Type != "A")`

2022-04-26 12:53 UTC, axilleastr commented on pkg/providers/cloudflare/dnsrecord.go
> +		if record.Name != fqdn || (record.Type != "TXT" && record.Type != "A") {
you are absolutely right. Dont know what I was thinking 🤦 
thanks

2022-04-26 13:21 UTC, hwoarang commented on pkg/providers/cloudflare/dnsrecord.go
> +		if record.Name != fqdn || (record.Type != "TXT" && record.Type != "A") {
yes you are right

2022-04-26 14:10 UTC, hwoarang commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
Why do we have a new `errr` variable here? can't we use `err` ? 🤔

2022-04-26 14:12 UTC, axilleastr commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
you mean why we create a new error? or why we name it `errr`?

2022-04-26 14:12 UTC, hwoarang commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
Yeah sorry I meant why not re-use the `err` variable ?

2022-04-26 14:15 UTC, axilleastr commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
the err variable gets a value once the [client.DeleteDNSRecord](https://github.com/gathertown/casper-3/pull/41/files#diff-021a0ca49e2dc5a2e2dcaf99c70d1496d0f8c3c6616722cc039f05d219531e70R306) being called. in our case,`client.DeleteDNSRecord` is not being called, so I would like to create and return an error, instead of returning just `false, nil`. Does that make sense?

2022-04-26 14:17 UTC, hwoarang commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
I does but I am asking a different thing :)

This
```
errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
```
uses a `errr` variable to get the error. What if we write this as
```
err := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
```
so we use `err` as variable again? Right now it seems a bit confusing to have both `err` and `errr` to capture errors. But maybe this is a common practice so feel free to ignore me :)

2022-04-26 14:19 UTC, axilleastr commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
ah sorry, I misunderstood the question. the `errr` can be named `err` again for sure. Actually, let me do that, since that looks:
1. better
2. more close to best/common practices

2022-04-26 14:29 UTC, axilleastr commented on pkg/providers/cloudflare/dnsrecord.go
> +			errr := fmt.Errorf("deleteRecord() wants to delete wrong record. Record Name: %v Record Type: %v", record.Name, record.Type)
done: https://github.com/gathertown/casper-3/commit/bff4c0e472887323dbd604eeadb43e35f91893f5

2022-04-26 14:30 UTC, hwoarang approved these changes

2022-04-28 07:06 UTC, atmosx approved these changes

2022-04-28 13:05 UTC, merged